---
title: "Re: Riak CS - Unable to create/view bucket details using dragon disk"
description: ""
project: community
lastmod: 2015-09-30T22:46:11-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg16580"
mailinglist_parent_id: "msg16579"
author_name: "Shunichi Shinohara"
project_section: "mailinglistitem"
sent_date: 2015-09-30T22:46:11-07:00
---


I asked some questions but the error stack did not answer any.

s/Dragon disk/s3cmd/ version of my questions:

- Does s3cmd actually attempt to connect to Riak CS?
 (instead of AWS S3)
- If yes, how does TCP communication go on?
- If TCP is ok, how is HTTP request/response?
- If HTTP is ok, what is the HTTP response status?

2015-10-01 12:44 GMT+09:00 G :
&gt; I get below error when I try to create a bucket using s3cmd
&gt;
&gt; Test access with supplied credentials? [Y/n] Y
&gt; Please wait, attempting to list all buckets...
&gt; Success. Your access key and secret key worked fine :-)
&gt;
&gt; Now verifying that encryption works...
&gt; Success. Encryption and decryption worked fine :-)
&gt;
&gt; Save settings? [y/N] y
&gt; Configuration saved to '/root/.s3cfg'
&gt;
&gt;
&gt;
&gt; root@ip-172-31-44-38:/etc/stanchion# s3cmd mb s3://test-bucket
&gt;
&gt; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
&gt; An unexpected error has occurred.
&gt; Please report the following lines to:
&gt; s3tools-b...@lists.sourceforge.net
&gt; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
&gt;
&gt; Problem: ParseError: mismatched tag: line 1, column 165
&gt; S3cmd: 1.1.0-beta3
&gt;
&gt; Traceback (most recent call last):
&gt; File "/usr/bin/s3cmd", line 1800, in 
&gt; main()
&gt; File "/usr/bin/s3cmd", line 1741, in main
&gt; cmd\\_func(args)
&gt; File "/usr/bin/s3cmd", line 158, in cmd\\_bucket\\_create
&gt; response = s3.bucket\\_create(uri.bucket(), cfg.bucket\\_location)
&gt; File "/usr/share/s3cmd/S3/S3.py", line 263, in bucket\\_create
&gt; response = self.send\\_request(request, body)
&gt; File "/usr/share/s3cmd/S3/S3.py", line 624, in send\\_request
&gt; raise S3Error(response)
&gt; File "/usr/share/s3cmd/S3/Exceptions.py", line 48, in \\_\\_init\\_\\_
&gt; tree = getTreeFromXml(response["data"])
&gt; File "/usr/share/s3cmd/S3/Utils.py", line 69, in getTreeFromXml
&gt; tree = ET.fromstring(xml)
&gt; File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
&gt; parser.feed(text)
&gt; File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
&gt; self.\\_raiseerror(v)
&gt; File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in
&gt; \\_raiseerror
&gt; raise err
&gt; ParseError: mismatched tag: line 1, column 165
&gt;
&gt; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
&gt; An unexpected error has occurred.
&gt; Please report the above lines to:
&gt; s3tools-b...@lists.sourceforge.net
&gt; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
&gt;
&gt;
&gt;
&gt;
&gt; --
&gt; View this message in context: 
&gt; http://riak-users.197444.n3.nabble.com/Riak-CS-Unable-to-create-view-bucket-details-using-dragon-disk-tp4033494p4033502.html
&gt; Sent from the Riak Users mailing list archive at Nabble.com.
&gt;
&gt; \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
&gt; riak-users mailing list
&gt; riak-users@lists.basho.com
&gt; http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com

\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\\_lists.basho.com

