---
title: "Re: Quick Q re: error"
description: ""
project: community
lastmod: 2012-11-09T09:10:17-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg09263"
mailinglist_parent_id: "msg09258"
author_name: "Sean Cribbs"
project_section: "mailinglistitem"
sent_date: 2012-11-09T09:10:17-08:00
---


Well, it's pretty obvious that it simply can't connect, especially
since your configuration is the default -- which means HTTP pointed to
127.0.0.1:8098. Is your Riak node running and on that port? Can you
hit it from curl on the command line?

On Fri, Nov 9, 2012 at 7:36 AM, Martin Streicher
 wrote:
&gt;
&gt; I'm not doing anything special in Riak::Client.
&gt;
&gt; How can I narrow what the RuntimeError is?
&gt;
&gt;
&gt;
&gt; On Nov 9, 2012, at 10:21 AM, Sean Cribbs wrote:
&gt;
&gt;&gt; Martin,
&gt;&gt;
&gt;&gt; How is your Riak::Client object configured? That looks like one of two
&gt;&gt; possibilities: first, the request failed 3 times in a row; second, one
&gt;&gt; of the backends is raising an exception that seems network related but
&gt;&gt; isn't one of the standard network errors (i.e it's a RuntimeError, but
&gt;&gt; it should be a SystemError with econnrefused errno!).
&gt;&gt;
&gt;&gt; On Fri, Nov 9, 2012 at 7:12 AM, Martin Streicher
&gt;&gt;  wrote:
&gt;&gt;&gt;
&gt;&gt;&gt; I get a connection refused error when I try to enable search from my code.
&gt;&gt;&gt;
&gt;&gt;&gt; /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:450:in
&gt;&gt;&gt; `rescue in recover\_from': Connection refused - connect(2) (RuntimeError)
&gt;&gt;&gt; from 
&gt;&gt;&gt; /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:422:in
&gt;&gt;&gt; `recover\_from'
&gt;&gt;&gt; from 
&gt;&gt;&gt; /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:284:in
&gt;&gt;&gt; `http'
&gt;&gt;&gt; from 
&gt;&gt;&gt; /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:129:in
&gt;&gt;&gt; `backend'
&gt;&gt;&gt; from 
&gt;&gt;&gt; /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:246:in
&gt;&gt;&gt; `get\_bucket\_props'
&gt;&gt;&gt; from 
&gt;&gt;&gt; /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/bucket.rb:77:in
&gt;&gt;&gt; `props'
&gt;&gt;&gt; from 
&gt;&gt;&gt; /var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/bucket.rb:68:in
&gt;&gt;&gt; `props='
&gt;&gt;&gt; from 
&gt;&gt;&gt; /var/www/zutron/releases/20121108191450/lib/classes/riak\_search.rb:6:in 
&gt;&gt;&gt; `enable\_search'
&gt;&gt;&gt;
&gt;&gt;&gt; enable\_search is:
&gt;&gt;&gt;
&gt;&gt;&gt; def self.enable\_search(bucket\_name, client = Riak::Client.new)
&gt;&gt;&gt; bucket = client.bucket bucket\_name
&gt;&gt;&gt; bucket.props = {search: true}
&gt;&gt;&gt; end
&gt;&gt;&gt;
&gt;&gt;&gt; Any ideas why it's failing? Search is enabled on the machine.
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt; \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
&gt;&gt;&gt; riak-users mailing list
&gt;&gt;&gt; riak-users@lists.basho.com
&gt;&gt;&gt; http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; --
&gt;&gt; Sean Cribbs 
&gt;&gt; Software Engineer
&gt;&gt; Basho Technologies, Inc.
&gt;&gt; http://basho.com/
&gt;



-- 
Sean Cribbs 
Software Engineer
Basho Technologies, Inc.
http://basho.com/

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

