---
title: "Re: not able to create schema"
description: ""
project: community
lastmod: 2011-02-23T09:07:35-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg02423"
mailinglist_parent_id: "msg02415"
author_name: "Doug Edmunds"
project_section: "mailinglistitem"
sent_date: 2011-02-23T09:07:35-08:00
---


On 2/23/2011 2:47 AM, wilson Tuladhar wrote:
&gt; now when I try to use this index name for indexing my document as :
&gt; search:index\_doc(&lt;&lt;"testindex"&gt;&gt;, &lt;&lt;"my\_doc"&gt;&gt;, [{&lt;&lt;"fname"&gt;&gt;,
&gt; &lt;&lt;"Fname"&gt;&gt;}, {&lt;&lt;"lname"&gt;&gt;, &lt;&lt;"Lname"&gt;&gt;}])
&gt; it gives me this error:
&gt; \*\* exception error: bad argument
&gt; in function ets:lookup/2
&gt; called as ets:lookup(schema\_table,&lt;&lt;"testUser"&gt;&gt;)
&gt; in call from riak\_search\_config:get\_schema/1
&gt; in call from riak\_indexed\_doc:new/4
&gt; in call from search:index\_doc/4
&gt; 
&gt; and when i check ets:all() i don't see schema\_table in the list??
&gt; 

Look at
http://erlangwiki.dougedmunds.com/doku.php?id=erlang:ets
and
http://stackoverflow.com/questions/1964990/erlang-ets-reset-ets-table-after-getting-a-bad-argument

When erlang (where ets comes from) throws an exception, it restarts the
shell (automatically, invisibly). The ets table you created in the
prior shell is destroyed, so checking ets:all() won't show it after the
restart.

Try checking ets:all() at a point just after you created it, but before
it throws the exception. Your table should be there.

- Doug Edmunds


\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

