---
title: "Re: RIAK TS installed nodes not connecting"
description: ""
project: community
lastmod: 2016-09-13T06:37:14-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg17641"
mailinglist_parent_id: "msg17640"
author_name: "Alex Moore"
project_section: "mailinglistitem"
sent_date: 2016-09-13T06:37:14-07:00
---


Joris,

One thing to check - since you are using a downloaded jar, are you using
the Uber jar that contains all the dependencies?
http://search.maven.org/remotecontent?filepath=com/basho/riak/spark-riak-connector\_2.10/1.6.0/spark-riak-connector\_2.10-1.6.0-uber.jar

Thanks,
Alex

On Tue, Sep 13, 2016 at 8:44 AM, Stephen Etheridge 
wrote:

&gt; Hi Joris,
&gt;
&gt; I have looked at the tutorial you have been following but I confess I am
&gt; confused. In the example you are following I do not see where the spark
&gt; and sql contexts are created. I use PySpark through the Jupyter notebook
&gt; and I have to specify a path to the connector on invoking the jupyter
&gt; notebook. Is it possible for you to share all your code (and how you are
&gt; invoking zeppelin) with me so I can trace everything through?
&gt;
&gt; regards
&gt; Stephen
&gt;
&gt; On Mon, Sep 12, 2016 at 3:27 PM, Agtmaal, Joris van &lt;
&gt; joris.vanagtm...@wartsila.com&gt; wrote:
&gt;
&gt;&gt; Hi
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; I’m new to Riak and followed the installation instructions to get it
&gt;&gt; working on an AWS cluster (3 nodes).
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; So far ive been able to use Riak in pyspark (zeppelin) to
&gt;&gt; create/read/write tables, but i would like to use the dataframes directly
&gt;&gt; from spark, using the Spark-Riak Connector.
&gt;&gt;
&gt;&gt; When following the example found here: http://docs.basho.com/riak/ts/
&gt;&gt; 1.4.0/add-ons/spark-riak-connector/quick-start/#python
&gt;&gt;
&gt;&gt; But i run into trouble on this last part:
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; host= my\_ip\_adress\_of\_riak\_node
&gt;&gt;
&gt;&gt; pb\_port = '8087'
&gt;&gt;
&gt;&gt; hostAndPort = ":".join([host, pb\_port])
&gt;&gt;
&gt;&gt; client = riak.RiakClient(host=host, pb\_port=pb\_port)
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; df.write \
&gt;&gt;
&gt;&gt; .format('org.apache.spark.sql.riak') \
&gt;&gt;
&gt;&gt; .option('spark.riak.connection.host', hostAndPort) \
&gt;&gt;
&gt;&gt; .mode('Append') \
&gt;&gt;
&gt;&gt; .save('test')
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; Important to note that i’m using a local download of the Jar file that is
&gt;&gt; loaded into the pyspark interpreter in zeppeling through:
&gt;&gt;
&gt;&gt; %dep
&gt;&gt;
&gt;&gt; z.reset()
&gt;&gt;
&gt;&gt; z.load("/home/hadoop/spark-riak-connector\_2.10-1.6.0.jar")
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; Here is the error message i get back:
&gt;&gt;
&gt;&gt; Py4JJavaError: An error occurred while calling o569.save. :
&gt;&gt; java.lang.NoClassDefFoundError: com/basho/riak/client/core/util/HostAndPort
&gt;&gt; at 
&gt;&gt; com.basho.riak.spark.rdd.connector.RiakConnectorConf$.apply(RiakConnectorConf.scala:76)
&gt;&gt; at 
&gt;&gt; com.basho.riak.spark.rdd.connector.RiakConnectorConf$.apply(RiakConnectorConf.scala:89)
&gt;&gt; at org.apache.spark.sql.riak.RiakRelation$.apply(RiakRelation.scala:115)
&gt;&gt; at 
&gt;&gt; org.apache.spark.sql.riak.DefaultSource.createRelation(DefaultSource.scala:51)
&gt;&gt; at org.apache.spark.sql.execution.datasources.ResolvedDataSourc
&gt;&gt; e$.apply(ResolvedDataSource.scala:222) at org.apache.spark.sql.DataFrame
&gt;&gt; Writer.save(DataFrameWriter.scala:148) at org.apache.spark.sql.DataFrame
&gt;&gt; Writer.save(DataFrameWriter.scala:139) at 
&gt;&gt; sun.reflect.NativeMethodAccessorImpl.invoke0(Native
&gt;&gt; Method) at 
&gt;&gt; sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
&gt;&gt; at 
&gt;&gt; sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
&gt;&gt; at java.lang.reflect.Method.invoke(Method.java:606) at
&gt;&gt; py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231) at
&gt;&gt; py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381) at
&gt;&gt; py4j.Gateway.invoke(Gateway.java:259) at py4j.commands.AbstractCommand.
&gt;&gt; invokeMethod(AbstractCommand.java:133) at 
&gt;&gt; py4j.commands.CallCommand.execute(CallCommand.java:79)
&gt;&gt; at py4j.GatewayConnection.run(GatewayConnection.java:209) at
&gt;&gt; java.lang.Thread.run(Thread.java:745) (&gt; 'py4j.protocol.Py4JJavaError'&gt;, Py4JJavaError(u'An error occurred while
&gt;&gt; calling o569.save.\n', JavaObject id=o570), &gt; 0x7f7021bb0200&gt;)
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; Hope somebody can help out.
&gt;&gt;
&gt;&gt; thanks, joris
&gt;&gt;
&gt;&gt; \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
&gt;&gt; riak-users mailing list
&gt;&gt; riak-users@lists.basho.com
&gt;&gt; http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
&gt;&gt;
&gt;&gt;
&gt;
&gt;
&gt; --
&gt; { "name" : "Stephen Etheridge",
&gt; "title" : "Solution Architect, EMEA",
&gt; "Organisation" : "Basho Technologies, Inc",
&gt; "Telephone" : "07814 406662",
&gt; "email" : "mailto:setheri...@basho.com",
&gt; "github" : "http://github.com/datalemming",
&gt; "twitter" : "@datalemming"}
&gt;
&gt;
&gt; \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
&gt; riak-users mailing list
&gt; riak-users@lists.basho.com
&gt; http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
&gt;
&gt;
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

