---
title: "Re: python-riak-client: 3 unit tests failed"
description: ""
project: community
lastmod: 2011-04-21T13:03:14-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg03115"
mailinglist_parent_id: "msg03114"
author_name: "Mathias Meyer"
project_section: "mailinglistitem"
sent_date: 2011-04-21T13:03:14-07:00
---


Mikhail,

thanks for bringing it to our attention, I've been noticing that one particular 
error (...expected 4) myself, and I'm planning to look into and fix it asap.

As for the other two, they fail because they require Riak Search. You can 
disable them by setting the environment variable SKIP\_SEARCH=1.

Mathias Meyer
Developer Advocate, Basho Technologies
On Donnerstag, 21. April 2011 at 21:49, Mikhail Sobolev wrote:
Hi,
> 
> (I'm not sure if this is a correct list for posting questions about
> python-riak-client. If it's not, please direct me to the correct
> forum.)
> 
> I downloaded:
> \* latest version of Riak (0.14.0-1 for Debian/32)
> \* the latest master of python-riak-client (git clone)
> 
> And run 'nosetests -v'. The outcome -- 3 failed test cases -- is a bit
> alarming (see below). Could anyone suggest what to look at?
> 
> Kind Regards,
> 
> --
> Misha
> 
> PS Just in case, it's python 2.6.6 on Ubuntu 10.10.
> 
> --- failed test cases ---
> ======================================================================
> ERROR: test\_search\_integration (riak.tests.test\_all.RiakHttpTransportTestCase)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "/home/mss/projects/derek/riak-python-client/riak/tests/test\_all.py", 
> line 395, in test\_search\_integration
> results = self.client.search("searchbucket", "foo:one OR foo:two").run()
> File "/home/mss/projects/derek/riak-python-client/riak/mapreduce.py", line 
> 185, in run
> result = t.mapred(self.\_inputs, query, timeout)
> File "/home/mss/projects/derek/riak-python-client/riak/transports/http.py", 
> line 198, in mapred
> result = json.loads(response[1])
> File "/usr/lib/python2.6/json/\_\_init\_\_.py", line 307, in loads
> return \_default\_decoder.decode(s)
> File "/usr/lib/python2.6/json/decoder.py", line 319, in decode
> obj, end = self.raw\_decode(s, idx=\_w(s, 0).end())
> File "/usr/lib/python2.6/json/decoder.py", line 338, in raw\_decode
> raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
> 
> ======================================================================
> ERROR: test\_search\_integration (riak.tests.test\_all.RiakPbcTransportTestCase)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "/home/mss/projects/derek/riak-python-client/riak/tests/test\_all.py", 
> line 395, in test\_search\_integration
> results = self.client.search("searchbucket", "foo:one OR foo:two").run()
> File "/home/mss/projects/derek/riak-python-client/riak/mapreduce.py", line 
> 185, in run
> result = t.mapred(self.\_inputs, query, timeout)
> File "/home/mss/projects/derek/riak-python-client/riak/transports/pbc.py", 
> line 300, in mapred
> msg\_code, resp = self.recv\_msg()
> File "/home/mss/projects/derek/riak-python-client/riak/transports/pbc.py", 
> line 349, in recv\_msg
> self.recv\_pkt()
> File "/home/mss/projects/derek/riak-python-client/riak/transports/pbc.py", 
> line 390, in recv\_pkt
> format(nmsglen))
> RiakError: Socket returned short packet length - expected 4
> 
> ======================================================================
> ERROR: test\_store\_of\_missing\_object 
> (riak.tests.test\_all.RiakPbcTransportTestCase)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "/home/mss/projects/derek/riak-python-client/riak/tests/test\_all.py", 
> line 369, in test\_store\_of\_missing\_object
> o = o.store()
> File "/home/mss/projects/derek/riak-python-client/riak/riak\_object.py", line 
> 277, in store
> Result = t.put(self, w, dw, return\_body)
> File "/home/mss/projects/derek/riak-python-client/riak/transports/pbc.py", 
> line 190, in put
> msg\_code, resp = self.recv\_msg()
> File "/home/mss/projects/derek/riak-python-client/riak/transports/pbc.py", 
> line 349, in recv\_msg
> self.recv\_pkt()
> File "/home/mss/projects/derek/riak-python-client/riak/transports/pbc.py", 
> line 390, in recv\_pkt
> format(nmsglen))
> RiakError: Socket returned short packet length - expected 4
> 
> ----------------------------------------------------------------------
> Ran 54 tests in 1.526s
> 
> FAILED (errors=3)
> 
> \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
> riak-users mailing list
> riak-users@lists.basho.com
> http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
> 


\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

