---
title: "Quick Q re: error"
description: ""
project: community
lastmod: 2012-11-09T07:12:43-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg09254"
author_name: "Martin Streicher"
project_section: "mailinglistitem"
sent_date: 2012-11-09T07:12:43-08:00

---



I get a connection refused error when I try to enable search from my code. 

/var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:450:in
 `rescue in recover\_from': Connection refused - connect(2) (RuntimeError)
 from 
/var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:422:in
 `recover\_from'
 from 
/var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:284:in
 `http'
 from 
/var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:129:in
 `backend'
 from 
/var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/client.rb:246:in
 `get\_bucket\_props'
 from 
/var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/bucket.rb:77:in
 `props'
 from 
/var/www/zutron/shared/bundle/ruby/1.9.1/gems/riak-client-1.0.5/lib/riak/bucket.rb:68:in
 `props='
 from 
/var/www/zutron/releases/20121108191450/lib/classes/riak\_search.rb:6:in 
`enable\_search'

enable\_search is:

def self.enable\_search(bucket\_name, client = Riak::Client.new)
 bucket = client.bucket bucket\_name
 bucket.props = {search: true}
end

Any ideas why it's failing? Search is enabled on the machine. 



 
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

