---
title: "Re: Can't delete objects from Riak KV"
description: ""
project: community
lastmod: 2016-04-14T06:52:26-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg17216"
mailinglist_parent_id: "msg17217"
author_name: "Alex De la rosa"
project_section: "mailinglistitem"
sent_date: 2016-04-14T06:52:26-07:00
---


I can try that, but I would like to do it via the python client itself...

Thanks,
Rohman

On Thu, Apr 14, 2016 at 5:47 PM, Luke Bakken  wrote:

> Hi Alex,
>
> Can you use the HTTP API to delete an object? Something like:
>
> curl -4vvv -XDELETE riak-host:8098/buckets/test/keys/something
>
> --
> Luke Bakken
> Engineer
> lbak...@basho.com
>
>
> On Thu, Apr 14, 2016 at 2:05 AM, Alex De la rosa
>  wrote:
> > I upgraded the Python library to the latest and is still failing... I'm
> > unable to delete any objects at all.
> >
> > ~ # pip show riak
> > ---
> > Name: riak
> > Version: 2.4.2
> > Location: /usr/local/lib/python2.7/dist-packages
> > Requires: six, pyOpenSSL, protobuf
> >
> > Everything else seems fine, just timeouts when deleting :(
> >
> > Thanks,
> > Alex
> >
> > On Thu, Apr 14, 2016 at 8:53 AM, Alex De la rosa <
> alex.rosa....@gmail.com>
> > wrote:
> >>
> >> Hi there,
> >>
> >> I'm trying to delete objects from riak with the python library and is
> >> timing out, any ideas? (this example is from a simple object, but also
> have
> >> issues with bucket types with map objects, etc...)... Just I seem to
> unable
> >> to delete anything, just times out.
> >>
> >> >>> import riak
> >> >>> RIAK = riak.RiakClient(protocol = 'pbc', nodes = [{'host':
> '--------',
> >> >>> 'http\_port': 8098, 'pb\_port': 8087}])
> >> >>> x = RIAK.bucket('test').get('something')
> >> >>> print x.data
> >> {"something":"here"}
> >> >>> x.delete()
> >> Traceback (most recent call last):
> >> File "", line 1, in 
> >> File "/usr/local/lib/python2.7/dist-packages/riak/riak\_object.py",
> line
> >> 329, in delete
> >> timeout=timeout)
> >> File
> "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
> >> line 196, in wrapper
> >> return self.\_with\_retries(pool, thunk)
> >> File
> "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
> >> line 138, in \_with\_retries
> >> return fn(transport)
> >> File
> "/usr/local/lib/python2.7/dist-packages/riak/client/transport.py",
> >> line 194, in thunk
> >> return fn(self, transport, \*args, \*\*kwargs)
> >> File
> "/usr/local/lib/python2.7/dist-packages/riak/client/operations.py",
> >> line 744, in delete
> >> pw=pw, timeout=timeout)
> >> File
> >>
> "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/transport.py",
> >> line 283, in delete
> >> riak.pb.messages.MSG\_CODE\_DEL\_RESP)
> >> File
> >>
> "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/connection.py",
> >> line 34, in \_request
> >> return self.\_recv\_msg(expect)
> >> File
> >>
> "/usr/local/lib/python2.7/dist-packages/riak/transports/pbc/connection.py",
> >> line 165, in \_recv\_msg
> >> raise RiakError(bytes\_to\_str(err.errmsg))
> >> riak.riak\_error.RiakError: 'timeout'
> >>
> >> My Riak version is 2.1.4
> >>
> >> My Python library is (installed via pip):
> >> Name: riak
> >> Version: 2.2.0
> >> Location: /usr/local/lib/python2.7/dist-packages
> >> Requires: six, pyOpenSSL, riak-pb
> >>
> >> Thanks,
> >> Alex
> >
> >
> >
> > \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
> > riak-users mailing list
> > riak-users@lists.basho.com
> > http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com
> >
>
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

