---
title: "Re: Riak errors after node left the cluster"
description: ""
project: community
lastmod: 2014-11-04T14:13:04-08:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg15117"
mailinglist_parent_id: "msg15116"
author_name: "Oleksiy Krivoshey"
project_section: "mailinglistitem"
sent_date: 2014-11-04T14:13:04-08:00
---


There were also errors during initial handoff, here is a full console.log
for that day: https://www.dropbox.com/s/o7zop181pvpxoa5/console.log?dl=0

I actually replaced two nodes that day. First one went smoothly as it
should. The second one resulted in the situation above. I replaced the
first one and then the second after few hours.

On 4 November 2014 20:44, Oleksiy Krivoshey  wrote:

> Hi,
>
> I'm running a 5 node cluster (Riak 2.0.0) and I had to replace hardware on
> one of the servers. So I did a 'cluster leave', waited till the node
> exited, checked the ring status and members status, all was ok, with no
> pending changes. Then later after about 5 minutes every client connection
> to any of the 4 remaining nodes started to fail with
>
> [Error: {error,mailbox\_overload}
>
> I have restarted one node after another and the error has gone. However I
> was still experiencing connectivity issues (timeouts) and riak error log is
> full of various errors even after I joined the 5th node back.
>
> Error are like:
>
> Failed to merge
> {["/var/lib/riak/bitcask\_expire\_1d/685078892498860742907977265335757665463718379520/1.bitcask.data"]
>
> gen\_fsm <0.818.0> in state active terminated with reason: bad record state
> in riak\_kv\_vnode:set\_vnode\_forwarding/2 line 991
>
> @riak\_pipe\_vnode:new\_worker:826 Pipe worker startup failed:
>
>
> msg,7,[{file,"gen\_fsm.erl"},{line,505}]},{proc\_lib,init\_p\_do\_apply,3,[{file,"proc\_lib.erl"},{line,239}]}]
> 2014-11-04 16:07:57.124 [error]
> <0.11128.0>@riak\_core\_handoff\_sender:start\_fold:279 hinted\_handoff transfer
> of riak\_kv\_vnode from 'riak@10.0.1.1'
> 353957427791078050502454920423474793822921162752 to 'riak@
> 10.0.1.5' 353957427791078050502454920423474793822921162752 failed because
> of error:undef
> [{riak\_core\_format,human\_size\_fmt,["~.2f",588],[]},{riak\_core\_handoff\_sender,start\_fold,5,[{file,"src/riak\_core\_han
> doff\_sender.erl"},{line,246}]}]
>
> The full error log file is available here:
> https://www.dropbox.com/s/3b8x3nqyego7lw3/error.log?dl=0
>
> There was no significant load on Riak so I would like to understand what
> caused so many errors?
>
> --
> Oleksiy
>



-- 
Oleksiy Krivoshey
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
riak-users mailing list
riak-users@lists.basho.com
http://lists.basho.com/mailman/listinfo/riak-users\_lists.basho.com

