---
title: "Riak 1.0.1 w/search nodes crashing"
description: ""
project: community
lastmod: 2011-10-28T11:47:04-07:00
sitemap:
  priority: 0.2
layout: mailinglistitem
mailinglist_id: "msg05348"
author_name: "Gordon Tillman"
project_section: "mailinglistitem"
sent_date: 2011-10-28T11:47:04-07:00
---


Howdy Gang,

We have a 3 node Riak 1.0.1 with search enabled and are seeing the following 
errors in the Riak log file:

==&gt; /var/log/riak/console.log &lt;==
2011-10-28 11:04:21.900 [error] &lt;0.993.0&gt; gen\\_fsm &lt;0.993.0&gt; in state initialize 
terminated with reason: bad argument in call to erlang:hd([]) in 
riak\\_core\\_ring:index\\_owner/2
2011-10-28 11:04:21.906 [error] &lt;0.993.0&gt; CRASH REPORT Process &lt;0.993.0&gt; with 0 
neighbours crashed with reason: bad argument in call to erlang:hd([]) in 
riak\\_core\\_ring:index\\_owner/2
2011-10-28 11:04:21.930 [error] &lt;0.257.0&gt; Supervisor riak\\_kv\\_keys\\_fsm\\_sup had 
child undefined started with {riak\\_core\\_coverage\\_fsm,start\\_link,undefined} at 
&lt;0.993.0&gt; exit with reason bad argument in call to erlang:hd([]) in 
riak\\_core\\_ring:index\\_owner/2 in context child\\_terminated

==&gt; /var/log/riak/crash.log &lt;==
2011-10-28 11:04:21 =ERROR REPORT====
\\*\\* State machine &lt;0.993.0&gt; terminating 
\\*\\* Last event in was timeout
\\*\\* When State == initialize
\\*\\* Data == 
{state,undefined,riak\\_kv\\_keys\\_fsm,{state,plain,{raw,60225046,&lt;0.465.0&gt;}},3,riak\\_kv,all,1,{'riak\\_kv\\_listkeys\\_req\\_v3',&lt;&lt;"queue"&gt;&gt;,none},60225046,undefined,0,60000,riak\\_kv\\_vnode\\_master}
\\*\\* Reason for termination = 
\\*\\* 
{badarg,[{erlang,hd,[[]]},{riak\\_core\\_ring,index\\_owner,2},{riak\\_core\\_coverage\\_plan,'-create\\_plan/5-fun-0-',6},{lists,mapfoldl,3},{riak\\_core\\_coverage\\_fsm,initialize,2},{gen\\_fsm,handle\\_msg,7},{proc\\_lib,init\\_p\\_do\\_apply,3}]}
2011-10-28 11:04:21 =CRASH REPORT====
 crasher:
 initial call: riak\\_core\\_coverage\\_fsm:init/1
 pid: &lt;0.993.0&gt;
 registered\\_name: []
 exception exit: 
{badarg,[{erlang,hd,[[]]},{riak\\_core\\_ring,index\\_owner,2},{riak\\_core\\_coverage\\_plan,'-create\\_plan/5-fun-0-',6},{lists,mapfoldl,3},{riak\\_core\\_coverage\\_fsm,initialize,2},{gen\\_fsm,handle\\_msg,7},{proc\\_lib,init\\_p\\_do\\_apply,3}]}
 in function gen\\_fsm:terminate/7
 in call from proc\\_lib:init\\_p\\_do\\_apply/3
 ancestors: [riak\\_kv\\_keys\\_fsm\\_sup,riak\\_kv\\_sup,&lt;0.177.0&gt;]
 messages: []
 links: [&lt;0.257.0&gt;]
 dictionary: []
 trap\\_exit: false
 status: running
 heap\\_size: 4181
 stack\\_size: 24
 reductions: 86192
 neighbours:
2011-10-28 11:04:21 =SUPERVISOR REPORT====
 Supervisor: {local,riak\\_kv\\_keys\\_fsm\\_sup}
 Context: child\\_terminated
 Reason: 
{badarg,[{erlang,hd,[[]]},{riak\\_core\\_ring,index\\_owner,2},{riak\\_core\\_coverage\\_plan,'-create\\_plan/5-fun-0-',6},{lists,mapfoldl,3},{riak\\_core\\_coverage\\_fsm,initialize,2},{gen\\_fsm,handle\\_msg,7},{proc\\_lib,init\\_p\\_do\\_apply,3}]}
 Offender: 
[{pid,&lt;0.993.0&gt;},{name,undefined},{mfargs,{riak\\_core\\_coverage\\_fsm,start\\_link,undefined}},{restart\\_type,temporary},{shutdown,5000},{child\\_type,worker}]


==&gt; /var/log/riak/erlang.log.3 &lt;==
11:04:21.900 [error] gen\\_fsm &lt;0.993.0&gt; in state initialize terminated with 
reason: bad argument in call to erlang:hd([]) in riak\\_core\\_ring:index\\_owner/2
11:04:21.906 [error] CRASH REPORT Process &lt;0.993.0&gt; with 0 neighbours crashed 
with reason: bad argument in call to erlang:hd([]) in 
riak\\_core\\_ring:index\\_owner/2 
11:04:21.930 [error] Supervisor riak\\_kv\\_keys\\_fsm\\_sup had child undefined 
started with {riak\\_core\\_coverage\\_fsm,start\\_link,undefined} at &lt;0.993.0&gt; exit 
with reason bad argument in call to erlang:hd([]) in 
riak\\_core\\_ring:index\\_owner/2 in context child\\_terminated

==&gt; /var/log/riak/error.log &lt;==
2011-10-28 11:04:21.900 [error] &lt;0.993.0&gt; gen\\_fsm &lt;0.993.0&gt; in state initialize 
terminated with reason: bad argument in call to erlang:hd([]) in 
riak\\_core\\_ring:index\\_owner/2
2011-10-28 11:04:21.906 [error] &lt;0.993.0&gt; CRASH REPORT Process &lt;0.993.0&gt; with 0 
neighbours crashed with reason: bad argument in call to erlang:hd([]) in 
riak\\_core\\_ring:index\\_owner/2
2011-10-28 11:04:21.930 [error] &lt;0.257.0&gt; Supervisor riak\\_kv\\_keys\\_fsm\\_sup had 
child undefined started with {riak\\_core\\_coverage\\_fsm,start\\_link,undefined} at 
&lt;0.993.0&gt; exit with reason bad argument in call to erlang:hd([]) in 
riak\\_core\\_ring:index\\_owner/2 in context child\\_terminated

Would anyone be able to clue me in as to the cause? I have the log snippet, 
status, and cluster info all available online.

LOG:
https://gist.github.com/1322665

STATUS:
https://gist.github.com/1322680

CLUSTER INFO:

This was to big to fit in a gist (1.7MB):

https://eval.mezeo.net/v2/files/A725C464-0194-11E1-9D55-0030485F2412/content/inline/cluster\\_info.txt

Thanks a bunch!

--gordon
